language: dart
dart:
  - "2.1.0"
stages:
  - test
  - name: deploy
    if: tag =~ ^([0-9]+\.){2,}[0-9]+$
jobs:
  include:
    - name: "formatting"
      script: dartfmt --dry-run --set-exit-if-changed .
    - name: "static analysis"
      script: dartanalyzer .
    - stage: deploy
      name: "deploy to pub"
      before_script: chmod +x tool/deploy.sh
      script: tool/deploy.sh